title: "Faris Doughan's Academic Website"
author:
  name: "Faris Doughan"
  email: "Farisdoughan@college.harvard.edu"
description: "Welcome to my academic website"
baseurl: ""
url: "https://farisdoughan.github.io"
markdown: kramdown
theme: minima
plugins:
  - github-pages
  - jekyll-feed