title: "Faris Doughan's Academic Website"
author:
  name: "Faris Doughan"
  email: "farisdoughan@example.com"
description: "Welcome to my academic website"
baseurl: ""
url: "https://farisdoughan.github.io"
markdown: kramdown
theme: minima
